# Generated by Django 3.2.16 on 2023-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
