# Generated by Django 3.2.16 on 2023-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='unverify', max_length=50),
        ),
    ]
