# Generated by Django 3.2.16 on 2023-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
