# Generated by Django 4.2.1 on 2023-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='coordinates',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
