# Generated by Django 3.2.16 on 2023-05-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
